### ISSUE TITLE
Change role order in role list

### ISSUE THREAD

**Issue by Apexal** [meew0/discordrb#119]
If possible, allow a role's position in the role list to be changed or set when creating one. This is important because it is currently possible for a bot with a role with all permissions allowed to create a role (and have it appear above the bot's role in the list) and then be unable to add it to users or further edit it due to lack of permissions.

**Comment by meew0** [comment]
I see how changing role position can be useful, but no account should be locked out of editing a role they created because new roles are always created at the bottom of the list, just above the @everyone role. (Unless it has MANAGE_ROLES due to the @everyone role, in which case they can't actually manage anything. This is a Discord limitation/bug)

**Comment by meew0** [comment]
Why close this? Reordering roles is still a valid feature request.

**Comment by meew0** [comment]
This has been put on hold because there are unforeseen difficulties with implementing role positioning. I'll revisit this eventually but it's not a priority given changing role order is a situational at best feature for a bot.
