### ISSUE TITLE
inconsistent use of alias_method

### ISSUE THREAD

**Issue by greenbigfrog** [meew0/discordrb#189]
I've noticed that [alias_method](https://github.com/meew0/discordrb/search?utf8=%E2%9C%93&q=alias_method) sometimes has a new line before it and sometimes not. I could PR this but I wanted to be sure which way you prefer it @meew0 (just styling issue :smile: )

**Comment by meew0** [comment]
The way it's supposed to be is a new line before every `alias_method`, except:
- if it follows another `alias_method`, regardless of whether the two are related in what they define
- if it follows another kind of meta-method (`attr_reader` etc.), but **only if** the `alias_method` directly relates to that meta method, i.e. defines an alias for the defined method, **and if** the meta method call doesn't take a multi-line block.
- if it is in a situation where new lines are explicitly forbidden, e.g. beginning of a class definition

Examples:

```rb
def cow_sound
  "Moo!"
end

alias_method :moo, :cow_sound
```

Here, a new line comes before the `alias_method`, even though the defined `:moo` alias relates to the method that precedes it. The same thing is the case if the relation does not exist:

```rb
def cow_sound
  "Moo"
end

def sheep_sound
  "Baa"
end

alias_method :moo, :cow_sound
alias_method :baa, :sheep_sound
```

Here, there is still a newline before the initial `alias_method` and its antecedent method definition, but none between the first `alias_method` and the second, even though both define aliases for different methods that aren't necessarily related. This relation is key if the `alias_method` follows another meta method:

```rb
attr_reader :name
alias_method :title, :name
```

Here, there is no newline between the `attr_reader` and the `alias_method`, for the reason that the alias_method defines an alias for that specific method. Consider the opposite case:

```rb
# ...
attr_reader :name

# ...
attr_reader :value

alias_method :title, :name
alias_method :worth, :value
```

Here we have a block of `alias_method`s after a block of `attr_reader`s, where the first `alias_method` doesn't relate to the last `attr_reader` that immediately precedes it. Hence, we add a new line here. (I added what would be the YARD comments between the `attr_reader`s so it's clear why there are newlines *there*.) I used `attr_reader` as an example for a meta method without a multi-line block - the case is different if there is one:

```rb
define_method :cow_sound do
  "Moo"
end

alias_method :moo, :cow_sound
```

Since `define_method` is a meta method, and the `alias_method` afterwards defines an alias for the defined method, there should not be a newline - but there is, because the meta method call takes a multi-line block. Note that inline blocks are fine without a newline (but obviously only if the `alias_method` relates to the defined method):

```rb
define_method(:cow_sound) { "Moo!" }
alias_method :moo, :cow_sound
```

However, all these rules are void if there is a reason where there cannot be a newline according to other style rules (e.g. Rubocop):

```rb
class Base
  def cow_sound
    "Moo"
  end
end

class Derived < Base
  alias_method :moo, :cow_sound
end
```

No matter the rules for `alias_method`, there should not be a newline at the beginning of a class definition (or any other block definition). I believe this is even enforced by Rubocop. 

I believe discordrb is mostly consistent by these guidelines - I only saw one inconsistency in GitHub search (which is, however, far from exhaustive). If you want to PR this, feel free; I hope you're not too intimidated by this...

**Comment by greenbigfrog** [comment]
Ok. Thanks. That made it a lot more clear for me. I'll need to look later at this when I've finished fixing up snazzahs PRs.

**Comment by greenbigfrog** [comment]
Ty!
