### ISSUE TITLE
[Question] Can you make a Selfbot?

### ISSUE THREAD

**Issue by jdhydra** [meew0/discordrb#192]
If you can how would you do it? It would be great if someone could tell me how with DiscordRB

**Comment by meew0** [comment]
Make it login to your own user account with `type: :user, token: '...'`. Enable `bot.should_parse_self = true`. Proceed as normal

**Comment by jdhydra** [comment]
Where? Ruby isnt really my thing, discord.js is what i use mostly

**Comment by meew0** [comment]
(Why not use discord.js for your selfbot then?)

The first thing has to be set as parameters in the bot initializer, i.e. `Discordrb::Bot.new`/`Discordrb::Commands::CommandBot.new`. The latter has to be done right after.

**Comment by jdhydra** [comment]
so, Discordrb::Commands::CommandBot.new::type: :user,

**Comment by meew0** [comment]
Create the bot like in any of the examples, but instead of token and app ID set token and type. All of this can also be found in the [documentation](http://www.rubydoc.info/github/meew0/discordrb/master/Discordrb%2FBot%3Ainitialize).

In the future, please use the discordrb channel on Discord for such questions.

**Comment by jdhydra** [comment]
ok
