### ISSUE TITLE
Strange issue when attempting to join a server using an invite

### ISSUE THREAD

**Issue by meew0** [meew0/discordrb#20]
Attempting to join a server using an invite code returns a HTTP 500 (Internal Server Error) with the following message:

`{"message": "'AnonymousUserMixin' object has no attribute 'id'"}`

**Relevant places in the code:**  
https://github.com/meew0/discordrb/blob/master/lib/discordrb/bot.rb#L92  
https://github.com/meew0/discordrb/blob/master/lib/discordrb/api.rb#L96

**Full stacktrace:**  
https://gist.github.com/meew0/4d6e9373974cfdb4d1a0

**Comment by davidkus** [comment]
Hey @meew0 

Thanks for setting up this project, I've been making great use of it!

After looking into this issue for a bit, it seems that the problem lies with the way `RestClient.post` is being called. `RestClient.post` expects the second parameter to be the payload (see [here](https://github.com/rest-client/rest-client/blob/master/lib/restclient.rb#L69), but you're providing the Authorization header as the second param. Sending an empty payload seems to solve this issue

```ruby
RestClient.post(
      "#{APIBASE}/invite/#{invite_id}",
      nil,
      Authorization: token
    )
```

Working on making a pull request for this, ill have it up in a bit.

**Comment by meew0** [comment]
Makes sense, I suspected it had something to do with RestClient. Thanks for the help!
