### ISSUE TITLE
Using `return` in a block should raise an exception

### ISSUE THREAD

**Issue by tom-sherman** [meew0/discordrb#355]
Following on from #354, the following code should raise an error:

```ruby
@bot.command :guard do |event, arg|
  return 'Guard' if true
end
```

As you can't use return like that in a block, you must use `next`. This error is suspected to be suppressed somewhere in the code.

**Comment by z64** [comment]
Yes it is. This is intentional for convenience ;

https://github.com/meew0/discordrb/blob/master/lib/discordrb/commands/parser.rb#L103-L104

https://github.com/meew0/discordrb/issues/47

This allows you to `break` or `return` out of command events without throwing the exception, while not expecting anything to be returned to discord, as this skips the rest of the `Command#call` execution entirely instead of `next`.

Additionally, a lot of bots probably already use `return` or `break` in this fashion, and there isn't anything inherently wrong with this if they are observing the behavior they want. I don't see any reason to remove this so they all suddenly start seeing errors in their console because they aren't using `next`.

If you'd like, we can document the behavior more clearly (".. rescues from LocalJumpError so that `return` and `break` can be used.."), but again, I don't think it's worth "breaking" bots over.

**Comment by tom-sherman** [comment]
No that makes sense, would be good to document this behaviour though.
