### ISSUE TITLE
Avoid GET-ing hidden channels, don't raise exceptions

### ISSUE THREAD

**Issue by csuhta** [meew0/discordrb#374]
The bot sometimes attempts to `GET` API information about a hidden channel, and it gets a 403 from Discord with "No Access". Then it raises a `Discordrb::Errors::NoPermission` and continues. This is harmless behavior, but it leads to a lot of annoyances developing with the bot:

- If you use an exception coalition service, it fills up with noise about these exceptions
- It's not obvious why you got this exception at first glance (see #373)
- If you hook into this error workflow, you will have to handle a lot of raised exceptions that are harmless

Raising and catching exceptions for semi-expected behavior like this is not a good workflow. Ruby exceptions are very expensive to toss.

I'm not sure about the difficulty of this but one of these would be more ideal:

- Avoid trying to `GET` a hidden channel beforehand somehow (not sure how you'd know the channel was hidden)
- RestClient supports a [block-style syntax](https://github.com/rest-client/rest-client#response-callbacks-error-handling) for methods which lets you inspect all parts of the process and doesn't raise exceptions on error codes. When you encounter a hidden channel, log a message but don't raise an exception.

**Comment by z64** [comment]
At the moment, the library doesn't really try to stop you from issuing bad requests in general, with a few exceptions I think. 

In general, there are a *lot* of cases to cover, and probably impossible to cover them all in detail. I'm not sure if it's really worth implementing more preemptive checking for a bad request other than the most common cases - for example, building embeds, which I have a WIP embed "linter" (#338) - and where the API currently doesn't give you a very helpful response (however, this changes in API v7, see my comment on your other issue #373).

In any case - You can tell if a channel is hidden if the current bot's member doesn't have `Read Messages` permission on that channel.

**Comment by csuhta** [comment]
The reason I opened this ticket specifically was because the library sometimes proactively GETs channel information (when a user starts typing or you get a message event,  I think). For example, I have a bot that's on an average of about 200 different servers, and I'm almost guaranteed to see this exception get raised less than 30 seconds after the bot boots.

I'm not requesting channel information directly, so I can't stop these requests from being issued.

**Comment by z64** [comment]
I'm sorry I don't quite understand. Discord does not send you gateway events from channels you do not have access to. (besides the channel itself changing, which does not require any permission other than being present in the guild)

**Comment by csuhta** [comment]
Here's some minimum code that shows an exception near boot for our bot and the server pool we listen to:

```ruby
require "discordrb"

# Produce more debugging information
module Discordrb::API
  def self.raw_request(type, attributes)
    RestClient.send(type, *attributes)
  rescue RestClient::Forbidden => error
    puts "Bot received an error 403 from Discord"
    puts "Type: #{type}"
    puts "Attributes: #{attributes}"
    puts "Response Body: #{error.response.body}"
    raise error
  end
end

@bot = Discordrb::Commands::CommandBot.new(token:ENV["DISCORD_BOT_TOKEN"], client_id:ENV["DISCORD_CLIENT_ID"], prefix: "/")
@bot.run
```

And the output:

```txt
Using WSCS version: 0.3.0
libsodium not available! You can continue to use discordrb as normal but voice support won't work.
        Read https://github.com/meew0/discordrb/wiki/Installing-libsodium for more details.
[INFO : websocket @ 2017-07-08 00:49:30.283] Discord using gateway protocol version: 6, requested: 6
Bot received an error 403 from Discord
Type: get
Attributes: ["https://discordapp.com/api/v6/channels/181125091751493634", {:Authorization=>"Bot REMOVED", :user_agent=>"rest-client/2.0.2 ruby/2.4.1p111 discordrb/3.2.1 DiscordBot (https://github.com/meew0/discordrb, v3.2.1) "}]
Response Body: {"code": 50001, "message": "Missing Access"}
[ERROR : websocket @ 2017-07-08 00:49:30.615] Gateway message error!
[ERROR : websocket @ 2017-07-08 00:49:30.615] Exception: #<RestClient::Forbidden: 403 Forbidden>
[ERROR : websocket @ 2017-07-08 00:49:30.615] /Users/Csuhta/.gem/ruby/2.4.1/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:223:in `exception_with_response'
[ERROR : websocket @ 2017-07-08 00:49:30.615] /Users/Csuhta/.gem/ruby/2.4.1/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:103:in `return!'
[ERROR : websocket @ 2017-07-08 00:49:30.615] /Users/Csuhta/.gem/ruby/2.4.1/gems/rest-client-2.0.2/lib/restclient/request.rb:809:in `process_result'
[ERROR : websocket @ 2017-07-08 00:49:30.615] /Users/Csuhta/.gem/ruby/2.4.1/gems/rest-client-2.0.2/lib/restclient/request.rb:725:in `block in transmit'
[ERROR : websocket @ 2017-07-08 00:49:30.615] /Users/Csuhta/.rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:877:in `start'
[ERROR : websocket @ 2017-07-08 00:49:30.615] /Users/Csuhta/.gem/ruby/2.4.1/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
[ERROR : websocket @ 2017-07-08 00:49:30.615] /Users/Csuhta/.gem/ruby/2.4.1/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
[ERROR : websocket @ 2017-07-08 00:49:30.615] /Users/Csuhta/.gem/ruby/2.4.1/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
[ERROR : websocket @ 2017-07-08 00:49:30.615] /Users/Csuhta/.gem/ruby/2.4.1/gems/rest-client-2.0.2/lib/restclient.rb:67:in `get'
[ERROR : websocket @ 2017-07-08 00:49:30.615] /Users/Csuhta/Projects/proj/lib/tasks/discord/run.rake:9:in `raw_request'
[ERROR : websocket @ 2017-07-08 00:49:30.615] /Users/Csuhta/.gem/ruby/2.4.1/gems/discordrb-3.2.1/lib/discordrb/api.rb:92:in `request'
[ERROR : websocket @ 2017-07-08 00:49:30.615] /Users/Csuhta/.gem/ruby/2.4.1/gems/discordrb-3.2.1/lib/discordrb/api/channel.rb:8:in `resolve'
[ERROR : websocket @ 2017-07-08 00:49:30.615] /Users/Csuhta/.gem/ruby/2.4.1/gems/discordrb-3.2.1/lib/discordrb/cache.rb:42:in `channel'
[ERROR : websocket @ 2017-07-08 00:49:30.615] /Users/Csuhta/.gem/ruby/2.4.1/gems/discordrb-3.2.1/lib/discordrb/data.rb:2612:in `update_data'
[ERROR : websocket @ 2017-07-08 00:49:30.616] /Users/Csuhta/.gem/ruby/2.4.1/gems/discordrb-3.2.1/lib/discordrb/data.rb:2247:in `initialize'
[ERROR : websocket @ 2017-07-08 00:49:30.616] /Users/Csuhta/.gem/ruby/2.4.1/gems/discordrb-3.2.1/lib/discordrb/cache.rb:149:in `new'
[ERROR : websocket @ 2017-07-08 00:49:30.616] /Users/Csuhta/.gem/ruby/2.4.1/gems/discordrb-3.2.1/lib/discordrb/cache.rb:149:in `ensure_server'
[ERROR : websocket @ 2017-07-08 00:49:30.616] /Users/Csuhta/.gem/ruby/2.4.1/gems/discordrb-3.2.1/lib/discordrb/bot.rb:785:in `create_guild'
[ERROR : websocket @ 2017-07-08 00:49:30.616] /Users/Csuhta/.gem/ruby/2.4.1/gems/discordrb-3.2.1/lib/discordrb/bot.rb:1120:in `handle_dispatch'
[ERROR : websocket @ 2017-07-08 00:49:30.616] /Users/Csuhta/.gem/ruby/2.4.1/gems/discordrb-3.2.1/lib/discordrb/bot.rb:586:in `dispatch'
[ERROR : websocket @ 2017-07-08 00:49:30.616] /Users/Csuhta/.gem/ruby/2.4.1/gems/discordrb-3.2.1/lib/discordrb/gateway.rb:652:in `handle_dispatch'
[ERROR : websocket @ 2017-07-08 00:49:30.616] /Users/Csuhta/.gem/ruby/2.4.1/gems/discordrb-3.2.1/lib/discordrb/gateway.rb:617:in `handle_message'
[ERROR : websocket @ 2017-07-08 00:49:30.616] /Users/Csuhta/.gem/ruby/2.4.1/gems/discordrb-3.2.1/lib/discordrb/gateway.rb:568:in `websocket_loop'
[ERROR : websocket @ 2017-07-08 00:49:30.616] /Users/Csuhta/.gem/ruby/2.4.1/gems/discordrb-3.2.1/lib/discordrb/gateway.rb:525:in `connect'
[ERROR : websocket @ 2017-07-08 00:49:30.616] /Users/Csuhta/.gem/ruby/2.4.1/gems/discordrb-3.2.1/lib/discordrb/gateway.rb:432:in `block in connect_loop'
[ERROR : websocket @ 2017-07-08 00:49:30.616] /Users/Csuhta/.gem/ruby/2.4.1/gems/discordrb-3.2.1/lib/discordrb/gateway.rb:431:in `loop'
[ERROR : websocket @ 2017-07-08 00:49:30.616] /Users/Csuhta/.gem/ruby/2.4.1/gems/discordrb-3.2.1/lib/discordrb/gateway.rb:431:in `connect_loop'
[ERROR : websocket @ 2017-07-08 00:49:30.616] /Users/Csuhta/.gem/ruby/2.4.1/gems/discordrb-3.2.1/lib/discordrb/gateway.rb:161:in `block in run_async'
```

**Comment by z64** [comment]
Ok. This particular trace looks like it's occuring while the bot is initially loading. I can take a closer look when I get home. 

If you like, you can join us on the discord API server in #ruby_discordrb and more efficiently disect this issue. I'm z64#2639.

**Comment by z64** [comment]
Hi @csuhta ,

I've looked deeply into this, and this particular exception is appearing because of your own code:
```rb
module Discordrb::API
  def self.raw_request(type, attributes)
    RestClient.send(type, *attributes)
  rescue RestClient::Forbidden => error
    puts "Bot received an error 403 from Discord"
    puts "Type: #{type}"
    puts "Attributes: #{attributes}"
    puts "Response Body: #{error.response.body}"
    raise error
  end
end
```
To understand this, there's a bit of a rabbit hole you have to follow. I'll step through your backtrace (backwards), but I'm going to be brief / skip over some parts:
```
[ERROR : websocket @ 2017-07-08 00:49:30.616] /Users/Csuhta/.gem/ruby/2.4.1/gems/discordrb-3.2.1/lib/discordrb/bot.rb:785:in `create_guild'
[ERROR : websocket @ 2017-07-08 00:49:30.616] /Users/Csuhta/.gem/ruby/2.4.1/gems/discordrb-3.2.1/lib/discordrb/bot.rb:1120:in `handle_dispatch'
[ERROR : websocket @ 2017-07-08 00:49:30.616] /Users/Csuhta/.gem/ruby/2.4.1/gems/discordrb-3.2.1/lib/discordrb/bot.rb:586:in `dispatch'
```
(again, read this backwards, from the bottom up)
1. We're connected, `READY`, and ready to learn about all of the guilds that we are connected to.
2. We got a `dispatch`.
3. It was a `GUILD_CREATE` - we start the process of caching it inside of `create_guild`.

We are here: <https://github.com/meew0/discordrb/blob/v3.2.1/lib/discordrb/bot.rb#L783-L786>

Next we start to store the server:
```
[ERROR : websocket @ 2017-07-08 00:49:30.616] /Users/Csuhta/.gem/ruby/2.4.1/gems/discordrb-3.2.1/lib/discordrb/cache.rb:149:in `ensure_server'
```
And start to store some of its properties with the internal `update_data` method:
```
[ERROR : websocket @ 2017-07-08 00:49:30.615] /Users/Csuhta/.gem/ruby/2.4.1/gems/discordrb-3.2.1/lib/discordrb/data.rb:2612:in `update_data'
```

We are here: <https://github.com/meew0/discordrb/blob/v3.2.1/lib/discordrb/data.rb#L2600-L2617>

There is then this block of code, called out in your backtrace:
```
[ERROR : websocket @ 2017-07-08 00:49:30.615] /Users/Csuhta/.gem/ruby/2.4.1/gems/discordrb-3.2.1/lib/discordrb/data.rb:2612:in `update_data'
```

Line 2612, from that trace, is the line where we cache the `@afk_channel`.
```rb
      begin
        @afk_channel = @bot.channel(@afk_channel_id, self) if @afk_channel_id.nonzero? && (!@afk_channel || @afk_channel_id != @afk_channel.id)
      rescue Discordrb::Errors::NoPermission
        LOGGER.debug("AFK channel #{@afk_channel_id} on server #{@id} is unreachable, setting to nil even though one exists")
        @afk_channel = nil
      end
```

**`@bot.channel(@afk_channel_id, self)` fails because we cannot access the AFK channel for whatever reason (it likely has Connect permissions denied on it)**

`#channel` attempts to call: <https://github.com/meew0/discordrb/blob/v3.2.1/lib/discordrb/cache.rb#L42>

This produces the `403 Forbidden` request, and **this is rescued by discordrb and raises the custom `Discordrb::NoPermission` exception**, which is in turn rescued inside of `update_data` to produce the `LOGGER.debug` lines shown above.

**However**, your patch raises this exception at a lower level inside of `raw_request`, so instead, the full stack trace is emitted to STDOUT. Normally, this exception would be raised and silently rescued like so, if you enable `log_mode: :debug`:

```
... "afk_channel_id"=>"243499489975992320"}}
[DEBUG : websocket @ 2017-07-08 02:40:12.597] Obtaining data for channel with id 243499489975992320
[DEBUG : websocket @ 2017-07-08 02:40:12.779] Tried to get access to restricted channel 243499489975992320, blacklisting it
[DEBUG : websocket @ 2017-07-08 02:40:12.779] AFK channel 243499489975992320 on server 225375815087554563 is unreachable, setting to nil even though one exists
```

.. and you would never see this exception at a higher logging mode (default). If I add your patch to my code, I get the same exact stack trace.

**All of that aside**, this does bring up an interesting issue with caching that with the `GUILD_CREATE` event, we actually do get all of the details for ALL of the channels regardless of permissions. It is specifically the `/channels/{cid}` route that is blocked, but  A) `GET /guilds/{gid}/channels` is not, B) all of the channels are in the gateway payload. 

But, because `update_data` - or rather the code that sets up the `@afk_channel` relationship to the cached channel - is called *before* `process_channels` ([called here](https://github.com/meew0/discordrb/blob/v3.2.1/lib/discordrb/data.rb#L2263), [implementation](https://github.com/meew0/discordrb/blob/v3.2.1/lib/discordrb/data.rb#L2704-L2714)), this data is not immediately available, and the `@afk_channel` is never actually established this way.

That, is indeed a caching bug.

If there are other exceptions, I'm happy to look into them, but be sure that your own patches are not getting in the way of other library behavior! :) (that said, we did find a bug..)

**Comment by csuhta** [comment]
@z64 thanks for this detailed write-up! Noted, and I'm glad I was able to reveal an internal caching issue.

**Comment by z64** [comment]
I'm going to treat this issue as a report for the uncovered channel caching bug, and defer to #373 for the enhancement that will be resolved when we get around to implementing v7 error objects.
