### ISSUE TITLE
VoiceBot stutter

### ISSUE THREAD

**Issue by davidsiaw** [meew0/discordrb#376]
When I create a simple voice bot and play an mp3

```ruby
        voice_chan = @bot.channel(chan_id)
        voice = @bot.voice_connect(voice_chan)
        voice.volume = @volume
        voice.play_file("sakura.mp3")
```

It seems to stutter at random moments. I am not sure if this is a known issue, or related to the slowness mentioned in the doc, but it is pretty crap. Could it have something to do with the file bitrate? Version of ffmpeg used? Perhaps I should use avconv?

**Comment by z64** [comment]
Hi there! Not sure which part of the docs you're speaking of - have you read this section?

http://www.rubydoc.info/gems/discordrb/Discordrb/Voice/VoiceBot

The parameters listed there are ones you would need to adjust for your performance / connection.

**Comment by davidsiaw** [comment]
Yes I have. Multiple times in fact, and I went through the sources to see what could be wrong. I have tried many values and the stutter is a seeming constant. The best performance I have found was with an adjust
_offset of 5 and adjust_interval of 50. I still get stutter.

**Comment by meew0** [comment]
You can also try using a DCA file instead of mp3; that should reduce stutter because no transcoding has to be done, meaning the total time spent on each packet is lowered. Other than that, keep trying different `adjust_` properties, in most cases there is a combination of values that reduces stuttering significantly (although it tends to be different for everyone). Also try `adjust_average` and `length_override` if you haven't already.

**Comment by meew0** [comment]
Closing this now as there hasn't been any activity, and the fundamental issue isn't really resolvable.
