### ISSUE TITLE
Returning an embed from a command should send the embed

### ISSUE THREAD

**Issue by LikeLakers2** [meew0/discordrb#393]
Title. Basically like how it already sends a returned string as a message, except with embeds instead of a string. Currently we have to manually send the embed ourselves, rather than let the library do it for us, otherwise we get something like `#<Discordrb::Webhooks::Embed:0x007f25f0126638>` sent to the channel.

On that note, we might also want to experiment with ways to allow someone to return both a string and an embed and have those sent as one message. Perhaps an array? Perhaps require a hash returned that's structured as such: `{ :message => 'text here', :embed => embed_we_made_earlier }`. It's not needed but it'd be useful.

**Comment by meew0** [comment]
I think this is a good request, but I'd rather delay this until 4.0.0 when the command system will be rewritten anyway.

**Comment by z64** [comment]
I agree that this is good and fits well with the existing CommandBot behaviour. As meew stated, the future of CommandBot isn't clear right now and needs to be discussed, which there will be a focused issue for in the future. Assuming we keep implicit returning in whatever form (I imagine we will) we should do this.

I'd be fine with merging a patch for this sooner because of that if someone wants to do one. In the meantime, I'm closing this to keep our issue tracker focused on being productive towards our short-term goals and library issues.
