### ISSUE TITLE
CommandBot does not support command names with spaces

### ISSUE THREAD

**Issue by soukouki** [meew0/discordrb#428]
```ruby
%s{a}==:a # => true

bot = Discordrb::Commands::CommandBot.new(
		token: token,
		client_id: client_id,
		prefix: "")
		
bot.command(%s{a b}){|e|"a b"}
bot.command(:c){|e|"c"}
bot.run
```
![image](https://user-images.githubusercontent.com/17077205/32318054-4f75ff52-bff9-11e7-9e2e-eee8ca241d1d.png)

**Comment by z64** [comment]
This is (you could say intentionally) not possible at the moment, as the parser derives the command name from the incoming string based on the string prior to the first space. In your example above, the command `:'a b'`, trying to parse this the parser tries to execute command `:a` which doesn't exist. So to me this is not a bug.
```rb
command_name = first_space ? command[0..first_space - 1] : command
```
https://github.com/meew0/discordrb/blob/master/lib/discordrb/commands/parser.rb#L216

I don't think it's possible to add this feature without making the command parser more complex, which we are trying to avoid completely right now as it's planned to rework the commands system eventually (post-4.0).

---

Anyways, you opened an issue but did not provide any description - what would you like us to do?
- We can add a disclaimer for now in the docs and wiki that command names cannot contain spaces.
- We can add an exception to raise if you try to do this (would rather not)
- If you want to add this feature, you can make a PR but I don't think it will get accepted right now.

There are likely workarounds if you really want this. There is a simple one and a more complex one.
- Simply, don't use a commands
```rb
bot.message(start_with: 'a b') do |event|
  # Maybe dispatch here to your own custom command system
end
```
- [Use a prefix proc](https://github.com/z64/discordrb/blob/171f963bdc6dcf1c4f3a9f868ed15d4ed2a86ab3/examples/prefix_proc.rb#L15-L40) to mutate the command chain in some appropriate way to trigger these commands. Probably difficult to do without creating other edge cases if you're not careful.

The first throws away the CommandBot and the second is very hacky. Writing commands without spaces or just using something like dashes (`-`), underscores (`_`), or dots (`.`) is IMO a small price to pay.

We can leave this open as a feature request, or maybe someone else has some other ideas on how to accomplish this.

**Comment by soukouki** [comment]
Thank you for your response.

**Comment by tripl3dogdare** [comment]
While I can't speak to command chaining as I haven't used it before, from a quick glance at the code it seems like this should be relatively easy to do by either:

- Moving the command/argument separation from `simple_execute` into `execute_command`.
- Moving the conversion from command name to Command instance from `execute_command` into `simple_execute`.

Out of the two, the former would probably be the better option in order to reduce the breakage resulting from the change. At that point, it comes down to implementation details. 

My initial thought would be to implement either a "most words first" (from right to left) or a "least words first" (from left to right) approach - this would essentially be a judgement call, as "least words first" would be more efficient for longer commands but be more likely to cause overlap issues with longer command names, where "most words first" would be less efficient for longer commands but ensure that shorter command names wouldn't prevent the longer command names from being used. I would personally opt for the "most words first" approach.

Here's a possible implementation idea:

```ruby
def execute_command(event, content, chained = false, check_permissions = true)
  command = nil
  arguments = []

  loop do
    command = @commands[content]
    break if command

    *content, arg = content.split(' ')
    content = content.join(' ')
    arguments.unshift(arg)
    break if content.length == 0
  end

  return unless # permission & channel checks
  unless command
    # ...
end
```

This isn't particularly optimized or necessarily following the lib's style rules, but it's just for illustration. An approach like this would loop through from the end of the command towards the beginning, successively trying smaller sets of space-separated pieces until it either ran out of pieces or found a command to execute. From there, the rest of `execute_command` would continue as it does so far.

Do note the change in `execute_command`'s signature here, removing the name parameter. This could be done as a non-breaking change with something like `content = name + arguments.join(' ')`, but this would be down to a judgement call.

Of course, this is all based on the current command parser. Hopefully it does give some ideas about what could be done to implement this, though =)

**Comment by z64** [comment]
The future of CommandBot as a whole needs to be discussed, and hopefully, the next iteration of it will more easily allow for more flexible parsing to enable something like this. For now, one can use the workarounds listed in this issue to write their own parser stage.
