### ISSUE TITLE
Ruby 2.5 Support on Windows

### ISSUE THREAD

**Issue by z64** [meew0/discordrb#455]
Currently, discordrb appears to fail to install on Windows because the following gems are not yet available under Ruby 2.5:
- `ffi`
```
ffi requires Ruby version < 2.5, >= 2.0. The current ruby version is 2.5.0
```
- `unf_ext`
```
unf_ext requires Ruby version < 2.5, >= 2.0. The current ruby version is 2.5.0
```
Ruby 2.4 can be used until these are updated or we find some kind of workaround.

(To be clear, Linux seems to be installing fine)

**Comment by Daniel-Worrall** [comment]
After going over this issue, it appears only the gem version uses `unf_ext`. Either a remnant of an old yard version or something else. I wasn't able to locate exactly where it's pulling it from as I'm not able to reproduce the error through `bundle install`, only through `gem install`.

As for master, it is still plagued by `ffi` being for previous Ruby versions. This is fixed in the master version of `ffi` but is not yet released as a gem version, unfortunately.

I went through the effort of locating each gem that uses ffi and had them forked, then patched in for them to require from master. I'm not convinced that it won't be broken when running a bot through it but it will at least compile.

If someone would like to take advantage on this (Keeping in mind, this is only a problem on Windows Ruby 2.5 and you can just use 2.4 or below instead), you can use this fork in bundler:
```gem 'discordrb', git: 'https://github.com/y32/discordrb.git', branch: '2.5'```

**Comment by z64** [comment]
We've upgraded our RestClient dependency in #478 and this has enabled us to run discordrb on Windows, but we're still testing the stability of it. If any of our master branch users experience uncommon issues on 2.5 in Windows using these updated dependencies, please feel free to report them here or in our chat.

**Comment by z64** [comment]
We haven't had any reports of issues since upgrading. I think we can close this for now, if anything new comes up, an issue can be opened up with more specific details.
