### ISSUE TITLE
Send error message when argument is not of specified Ruby type

### ISSUE THREAD

**Issue by wRadion** [meew0/discordrb#522]
Hello,

I have a suggestion.
Right now, the `arg_types` argument is used to coerce the typed arguments to Ruby types. But if the cast fails, it does nothing and sends nothing to the user. It would be a good thing to send an error message saying that the argument should be a specific type to let the user know he typed the right command, but with the wrong arguments.

I say this because the arguments count sends a message to the user saying there was not the right argument count. So, for consistency, it should also sends a message if the types are not valid.

This is most applicable to `Integer` arguments.

What do you guys think?

**Comment by z64** [comment]
Hi @wRadion,

I know we talked about this in Discord a bit, but just to reiterate: A patch is still welcome if you want to pull one together but I don't think we will plan on doing this yet otherwise. There will be a discussion issue for CommandBot in the near future where we'll be focusing on what we want in/out as far as features goes to support a productive refactoring, where hopefully it will be much easier to extend on your part without having to get your hands dirty, so to speak. We will consider this along with all other command bot feature requests we've had over the past cycle.

Going to close this since we haven't had any movement, thanks again for your interest and support :heart:, any questions, feel free to reopen/comment/drop us a line in chat.
