### ISSUE TITLE
Parse JSON embed

### ISSUE THREAD

**Issue by rokhimin** [meew0/discordrb#651]
I try this and work
```
command(:latest) do |event|
                api = "https://andien.com/api/....."
                url = api
                uri = URI(url)
                response = Net::HTTP.get(uri)
                data = JSON.parse(response)
                event.respond "Latest post #{ title = data["post"]["last"] }"
end
```
.
but I need embed
```
command(:latest) do |event|
                api = "https://andien.com/api/....."
                url = api
                uri = URI(url)
                response = Net::HTTP.get(uri)
                data = JSON.parse(response)
                servers = event.bot.servers 
                event.channel.send_embed do |embed| 
                embed.colour = 0xff8040 
                embed.add.field = name: "Latest post", value: " #{ title = data["post"]["last"] }"
end
```
.
does't not work . message syntax error

**Comment by VxJasonxV** [comment]
`embed.add` is not a method. Check out https://leovoel.github.io/embed-visualizer/ , click 'Generate Code' at the bottom, change the language to "discordrb (Ruby)". Examine how it is accomplishing additional fields.

**Comment by Daniel-Worrall** [comment]
Hi there, thanks for using discordrb.

We'd prefer to use Issues to report problems with the library or suggestions for improvement, while supporting various usage questions through the docs/wiki/tutorials and of course the discord channel where many users can talk to each other in real time. See [here](https://discord.gg/cyK3Hjm)

The problem here is the misuse of adding a field to the embed. You've entered `event.add.field`, where you probably meant to put `embed.add_field`. If you have further problems, please join the discord and let us know. We're happy to help
