### ISSUE TITLE
play_dca doesn't respect volume attribute

### ISSUE THREAD

**Issue by teschnei** [meew0/discordrb#82]
play_dca plays the DCA file full volume regardless of what the VoiceBot's volume attribute is set to.

**Comment by meew0** [comment]
Yes, this is unfortunately unavoidable because modifying the volume involves either sending volume data as a filter to FFmpeg (which isn't being used when playing DCA) or manually multiplying PCM values. The latter is impractical because it would involve decoding each frame, modifying the volume and encoding it again, which defeats the entire purpose of DCA (no recoding). If you want to change DCA volume, you'll have to do it while encoding.

I'll extend the docs to clarify this.

**Comment by teschnei** [comment]
That's what I did end up doing, I appreciate the response and the doc
update :)
