### ISSUE TITLE
Make "disconnected from WS" "error" to one line

### ISSUE THREAD

**Issue by green-big-frog** [meew0/discordrb#90]
ATM it kinda looks a bit dramatically: 
```
[ERROR : gateway @ 2016-04-14 10:40:20.173] Disconnected from WebSocket!
[ERROR : gateway @ 2016-04-14 10:40:20.173]  (Reason: )
[ERROR : gateway @ 2016-04-14 10:40:20.173]  (Code: 1001)
[ERROR : gateway @ 2016-04-14 10:40:20.173] Disconnected from WebSocket!
[WARN : websocket @ 2016-04-14 10:40:20.173] Oh dear, we got disconnected!
```

Making this one line might be a good idea. Also maybe post a msg if the bot successfully reconnected.

**Comment by meew0** [comment]
The reason for the "Oh dear" message is because it happens on a separate thread - the "Disconnected from WebSocket" message means the WS received a close frame (with code and reason) and should stop its thread, the "Oh dear, we got disconnected" means the thread has exited to the reconnection logic. I see how this can be a little overwhelming, I'll try to make it more compact
