### ISSUE TITLE
Defining custom rate limit message for Bucket

### ISSUE THREAD

**Issue by PoVa** [meew0/discordrb#93]
Instead of having to define custom rate limit message for every command, it would be nice if you could define one and it would work with every command that has this bucket added.

**Comment by meew0** [comment]
On second thought, this can't really be done in a good way because internally, buckets/rate limiters are decoupled from Discord (it just happens that command containers can use them directly). You can use rate limiters without ever making any kind of bot, and having a separate message parameter would screw with this separation.
